### ISSUE TITLE
The number of NMS

### ISSUE THREAD

**Issue by hangxu124** [neeharperi/FutureDet#8]
Hi @neeharperi ,
Thanks for sharing your code. 
I have a question about the algorithm. It seems that we need to do N+1 times NMS (for example, 7 times NMS if we predict 6 future frames) if we predict N frames before the back-casting tracking. I'd like to know if there is some method that we do not need to do many NMS.
Thanks again!

**Comment by neeharperi** [comment]
We need to perform NMS on each timestep independently to avoid suppressing future detections from stationary objects. You may be able to modify the NMS code to take into consideration the timestep of each future prediction to avoid the issue described above so you only need to run NMS once. 

I am currently working on a newer version of this code that is based on the mmdetection3d framework, supports nuScenes and Argoverse 2, and allows for multi-class FutureDet. I can try to address this problem here. I expect to release this in the next few days.
